name: bejoy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-169.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
      - family: Galyon
        fonts:
          - asset: lib/design/fonts/Galyon-Book.otf
          - asset: lib/design/fonts/Galyon-Bold.otf
            
      - family: Pro
        fonts:
          - asset: lib/design/fonts/PrimeformProDemo-Regular.otf
            weight: 700
  assets:
    - lib/design/logos/willow_color_TXT.png
    - lib/design/logos/kanji.png
          
